config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  get 'search', to: "pages#search", as: "search"

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   registrations: 'users/registrations' }

  root to: 'pages#home'



  resources :pony_offers, only: [:index, :destroy]
  resources :bookings, only: [:index, :show]



  resources :ponies do
    resources :pony_offers, only: [:new, :create, :list, :show ] do
      resources :bookings, except: [ :update, :edit, :index ]
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pony_offer.rb
class PonyOffer < ApplicationRecord
  belongs_to :pony
  has_one :user, through: :pony
  has_many :bookings

  validates :pony_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :daily_rate, presence: true

  before_create :mark_most_recent

  # Once we create a new pony_offer for a certain pony, it will mark its previous most recent offer as most_recent=false
  # Doing so, we will be able to track the active offers for a certain pony, there can indeed be only one active offer per
  # pony
  def mark_most_recent
    unless self.pony.pony_offers.empty?
      previous_recent_offer = self.pony.pony_offers.order(:created_at => :asc).last
      previous_recent_offer.most_recent = false
      previous_recent_offer.save
    end
  end

  def unavailable_dates
    result_array = []
    if self.bookings.empty?
      return []
    else
      self.bookings.each do |booking|
        booking.dates.each do |date|
          result_array << date.strftime('%-m-%-d-%Y')
        end
      end
    end
    result_array.unshift((Date.today - 1).strftime('%-m-%-d-%Y'))
  end

  def available?(booking)
    dates = booking.dates
    dates.each do |date|
      return false if self.unavailable_dates.include?(date.strftime('%-m-%-d-%Y'))
    end
    start = booking.start_date
    finish = booking.end_date
    if self.start_date > start || self.end_date < finish
      return false
    end
    true
  end
end

app/controllers/pony_offers_controller.rb
class PonyOffersController < ApplicationController

  before_action :set_pony_offer, only: [:show, :destroy]
  skip_before_action :authenticate_user!, only: :show


  # method do list all offers from one user
  def index
    @pony_offers = current_user.owned_pony_offers
    @active_pony_offers = @pony_offers.where(most_recent: true)
  end

  # method do list all offers associated with one pony
  def list
    @pony = Pony.find(params[:pony_id])
    @pony_offers = @pony.pony_offers
  end

  # Done
  def show
    @pony = @pony_offer.pony
    @pony_coordinates = { lat: @pony.latitude, lng: @pony.longitude }
    # Stores the informations required to display Google maps in a Hash
    unless @pony_coordinates[:lat].nil?
      @hash = Gmaps4rails.build_markers([@pony]) do |pony, marker|
        marker.lat pony.latitude
        marker.lng pony.longitude
      end
    end
    @to_disable_dates = @pony_offer.unavailable_dates
  end

  def new
    # User can only create a new offer if the pony belongs to him, if not redirect user to the root
    @pony = Pony.find(params[:pony_id])
    if @pony.user.id == current_user.id
      @pony_offer = PonyOffer.new
    else
      redirect_to root_path, notice: "Selected pony does not belong to current user"
    end
  end

  def create
    @pony_offer = PonyOffer.new(pony_offer_params)
    @pony_offer.most_recent = true
    @pony = Pony.find(params[:pony_id])
    @pony_offer.pony = @pony


    if @pony_offer.save
      redirect_to root_path, notice: "Pony offer was successfully created"
    else
      render :new
    end

  end

  def destroy
    @pony_offer.destroy
    redirect_to pony_offers_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pony_offer
      @pony_offer = PonyOffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pony_offer_params
      params.require(:pony_offer).permit(:start_date, :end_date, :daily_rate)
    end

end

app/helpers/pony_offers_helper.rb
module PonyOffersHelper
end

app/views/pony_offers/_form.html.erb
<%= simple_form_for @pony_offer, method: "post", url: pony_pony_offers_path do |f| %>
  <div class="form-group">
    <%= f.input :start_date, label: "Please enter the start date of your offer: ", as: :date, input_html: {class: "form-control"} %>
    <%= f.input :end_date, label: "Please enter the end date of your offer: ", as: :date, input_html: {class: "form-control"} %>
    <%= f.input :daily_rate, label: "Please enter the offer's daily rate: ", input_html: {class: "form-control"} %>
  </div>

  <br>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/pony_offers/_offer_booking_form.html.erb
<%= simple_form_for @booking, method: "get", url: new_pony_pony_offer_booking_path(@pony_offer.pony, @pony_offer) do |f| %>
  <div class="form-group" >
    <%= f.input :start_date, label: "Please enter desired start date of your booking: ", as: :string, input_html: {class: "form-control", id: "datepicker_start_date", placeholder: "dd/mm/yyyy"} %>
    <%= f.input :end_date, label: "Please enter the desired end date of your booking: ", as: :string, input_html: {class: "form-control", id: "datepicker_end_date"}, placeholder: "dd/mm/yyyy" %>
  </div>

  <br>
  <%= f.button :submit, class: "btn btn-brand", value: "Book this pony" %>
<% end %>

app/views/pony_offers/create.html.erb
<h1>PonyOffers#create</h1>
<p>Find me in app/views/pony_offers/create.html.erb</p>

app/views/pony_offers/destroy.html.erb
<h1>PonyOffers#destroy</h1>
<p>Find me in app/views/pony_offers/destroy.html.erb</p>

app/views/pony_offers/edit.html.erb
<h1>PonyOffers#edit</h1>
<p>Find me in app/views/pony_offers/edit.html.erb</p>

app/views/pony_offers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h3>My active pony listings:</h3>
      <% @active_pony_offers.each do |offer| %>

        <% offer.most_recent ? status = "active" : status = "old" %>
        <p> Pony offer: <%= offer.id %> - Pony: <%= offer.pony.name %> - <%=link_to 'show', pony_pony_offer_path(offer.pony, offer)%> - Status: <%= status  %> </p>
      <% end %>

      <h3>My old pony listings:</h3>
      <% @pony_offers.each do |offer| %>

      <% offer.most_recent ? status = "active" : status = "old" %>
        <% unless offer.most_recent %>
          <p> Pony offer: <%= offer.id %> - Pony: <%= offer.pony.name %> - <%=link_to 'show', pony_pony_offer_path(offer.pony, offer)%> - Status: <%= status  %> </p>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= link_to "My Ponies", ponies_path, class:"btn btn-primary" %>
</div>

app/views/pony_offers/new.html.erb
<h1>New PonyOffer</h1>

<%= render 'form', pony_offer: @pony_offer %>

<%= link_to 'Back', pony_path(@pony) %>

app/views/pony_offers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h2> Pony Offer number <%= @pony_offer.id %></h2>
        <p> Start date: <%= @pony_offer.start_date%></p>
        <p> End date: <%= @pony_offer.end_date%></p>
        <p> Daily rate: <%= @pony_offer.daily_rate%></p>

        <% %w(name color age race description location). each do |method|  %>
          <% value = @pony_offer.pony[method.to_sym]  %>
          <% unless value.nil? || value.strip == "" %>
            <p> <strong><%= method.capitalize %></strong> - <%= value %> </p>
          <% end %>
        <% end %>

        <h3>Description</h3>
        <p><%= @pony_offer.pony.description %></p>

        <!-- Checks if the current user is the owner of the listed pony if now, we will see a button for bookings -->
        <% if @pony_offer.pony.is_owner?(current_user)  %>
          <%= link_to 'delete offer',  pony_offer_path(@pony_offer), method: 'delete' %>
          <br>
          <%= link_to 'Back to my listing',  pony_offers_path %>
        <% else %>
          <br>
          <% @booking = Booking.new %>
          <%= render "offer_booking_form", booking: @booking  %>
        <% end %>
    </div>
    <div class="col-xs-6">
      <div id="map" style="width: 100%; height: 400px; margin: 20px;"></div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    /* PART FOR GOOGLE MAPS */
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(8);
        }
      });
    });



    /* PART FOR DISABLING DATEPICKER DAYS */
    var disabledDays = <%= raw @to_disable_dates %>;

    /* utility functions */
    function unavailableDays(date) {
      var m = date.getMonth(), d = date.getDate(), y = date.getFullYear();
      for (i = 0; i < disabledDays.length; i++) {
        if($.inArray((m+1) + '-' + d + '-' + y,disabledDays) != -1 || new Date() > date) {
          return [false];
        }
      }
      return [true];
    }


    /* create datepicker for start date and end date */
    <% max_date = @pony_offer.end_date.strftime('%-m-%-d-%Y')  %>
    <% Date.today <= @pony_offer.start_date ? min_date = @pony_offer.start_date.strftime('%-m-%-d-%Y') : min_date = Date.today.strftime('%-m-%-d-%Y')  %>


      $('#datepicker_end_date').datepicker({
        dateFormat: 'dd/mm/yy',
        constrainInput: true,
        beforeShowDay: unavailableDays,
        maxDate: new Date(<%= raw [max_date] %>)
      });

      $('#datepicker_start_date').datepicker({
        dateFormat: 'dd/mm/yy',
        constrainInput: true,
        beforeShowDay: unavailableDays,
        maxDate: new Date(<%= raw [max_date] %>),
        minDate: new Date(<%= raw [min_date] %>),
        onClose: function(selectedDate) {
          $("#datepicker_end_date").datepicker("option", "minDate", selectedDate );
          $("#datepicker_end_date").focus();
        }
      });
  </script>
<% end %>

app/views/pony_offers/update.html.erb
<h1>PonyOffers#update</h1>
<p>Find me in app/views/pony_offers/update.html.erb</p>