config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  get 'search', to: "pages#search", as: "search"

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   registrations: 'users/registrations' }

  root to: 'pages#home'



  resources :pony_offers, only: [:index, :destroy]
  resources :bookings, only: [:index, :show]



  resources :ponies do
    resources :pony_offers, only: [:new, :create, :list, :show ] do
      resources :bookings, except: [ :update, :edit, :index ]
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pony_offer

  validates :user_id, presence: true
  validates :pony_offer_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :price, presence: true

  def duration
    (self.end_date - self.start_date).to_i + 1
  end

  def dates
    current_date = self.start_date
    result_array = []
    while current_date <= self.end_date
      result_array << current_date
      current_date += 1
    end
    result_array
  end

  # Checks is physically overdue meaning that its over
  def old?
    self.end_date || self.end_date < Date.today
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @rented_bookings = current_user.rented_bookings
    @owned_bookings = current_user.owned_bookings
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @pony_offer = PonyOffer.find(params[:pony_offer_id])
    @pony = @pony_offer.pony
    @booking = Booking.new(booking_params(params))
    @price = @booking.duration * @pony_offer.daily_rate
    @to_disable_dates = @pony_offer.unavailable_dates
    @error = !@pony_offer.available?(@booking)
  end

  def create
    @pony_offer = PonyOffer.find(params[:pony_offer_id])
    @pony = @pony_offer.pony
    @booking = Booking.new(booking_params(params))
    @booking.price = @booking.duration * @pony_offer.daily_rate
    @booking.user = current_user
    @booking.pony_offer = @pony_offer
    @booking.save
    redirect_to booking_path(@booking)
  end

  def destroy
  end

  private

  def booking_params(params)
    {start_date: Date.parse(params[:booking][:start_date]), end_date: Date.parse(params[:booking][:end_date])}
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking_form.html.erb
<%= simple_form_for @booking, method: "post", url: pony_pony_offer_bookings_path(@pony, @pony_offer) do |f| %>
  <div class="form-group">
    <%= f.input :start_date, label: "Start date of your booking: ", as: :string, input_html: {class: "form-control", id: "datepicker_start_date", placeholder: "dd/mm/yyyy"} %>
    <%= f.input :end_date, label: "End date of your booking: ", as: :string, input_html: {class: "form-control", id: "datepicker_end_date"}, placeholder: "dd/mm/yyyy" %>
  </div>


  <br>
  <%= f.button :submit, class: "btn btn-primary", value: "Confirm Booking" %>
<% end %>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/index.html.erb
<h1>My Bookings</h1>

<h2>My rented ponies</h2>
<% @rented_bookings.each do |booking| %>
  <p> Pony booking: <%= booking.id %> - Pony: <%= booking.pony_offer.pony.name %> - From <%= booking.start_date  %> to <%= booking.end_date  %> - <strong>Renter:</strong> <%= booking.user.first_name  %> - <strong>Owner:</strong> <%= booking.pony_offer.pony.user.first_name  %> </p>
<% end %>


<h2>My owned ponies on rent</h2>
<% @owned_bookings.each do |booking| %>
  <p> Pony booking: <%= booking.id %> - Pony: <%= booking.pony_offer.pony.name %> - From <%= booking.start_date  %> to <%= booking.end_date  %> - <strong>Renter:</strong> <%= booking.user.first_name  %> - <strong>Owner:</strong> <%= booking.pony_offer.pony.user.first_name  %> </p>
<% end %>

app/views/bookings/new.html.erb
<h1>Confirm your booking</h1>

<% if @error %>
  <h3 style="color:red;"> UNAVAILABLE DUDE </h3>
<% else %>
  <h3>The total price of your booking is <%= @price  %> euros</h3>
  <%= render 'booking_form', booking: @booking %>
<% end %>

<%= link_to 'Back', pony_path(@pony) %>

<% content_for(:after_js) do %>
  <script>

    /* PART FOR DISABLING DATEPICKER DAYS */
    var disabledDays = <%= raw @to_disable_dates %>;

    /* utility functions */
    function unavailableDays(date) {
      var m = date.getMonth(), d = date.getDate(), y = date.getFullYear();
      for (i = 0; i < disabledDays.length; i++) {
        if($.inArray((m+1) + '-' + d + '-' + y,disabledDays) != -1 || new Date() > date) {
          return [false];
        }
      }
      return [true];
    }


    /* create datepicker for start date and end date */
    <% max_date = @pony_offer.end_date.strftime('%-m-%-d-%Y')  %>

      $('#datepicker_end_date').datepicker({
        dateFormat: 'dd/mm/yy',
        constrainInput: true,
        beforeShowDay: unavailableDays,
        maxDate: new Date(<%= raw [max_date] %>)
      });

      $('#datepicker_start_date').datepicker({
        dateFormat: 'dd/mm/yy',
        constrainInput: true,
        beforeShowDay: unavailableDays,
        maxDate: new Date(<%= raw [max_date] %>),
        onClose: function(selectedDate) {
          $("#datepicker_end_date").datepicker("option", "minDate", selectedDate );
          $("#datepicker_end_date").focus();
        }
      });
  </script>
<% end %>

app/views/bookings/show.html.erb
<h1>My Booking</h1>
<h2> Pony Bookingnumber <%= @booking.id %></h2>


<p> Start date: <%= @booking.start_date%></p>
<p> End date: <%= @booking.end_date%></p>
<p> Daily rate: <%= @booking.pony_offer.daily_rate%></p>
<p> Total price: <%= @booking.price%></p>

<ul>

<li><%= @booking.pony_offer.pony.name %></li>
<li><%= @booking.pony_offer.pony.location %></li>
<li><%= @booking.pony_offer.pony.color %></li>
<li><%= @booking.pony_offer.pony.age %></li>

</ul>

<h3>Description</h3>
<p><%= @booking.pony_offer.pony.description %></p>