config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  get 'search', to: "pages#search", as: "search"

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   registrations: 'users/registrations' }

  root to: 'pages#home'



  resources :pony_offers, only: [:index, :destroy]
  resources :bookings, only: [:index, :show]



  resources :ponies do
    resources :pony_offers, only: [:new, :create, :list, :show ] do
      resources :bookings, except: [ :update, :edit, :index ]
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="welcome-text">
        <h1><span class="brand-color boldest">Welcome to Rent-a-Pony.</span> Unleash the Cow-Boy in you and book one of our stallions!</h1>
      </div>
      <form action="<%= search_path %>" class="form-inline search-container">
        <div class="container">
          <div class="row">
            <div class="col-xs-3">
              <div class="form-group">
                <label for="start_date" class="">From:</label>
                <input type="date" placeholder="From" name="start_date" id="start_date" class="form-control">
              </div>
            </div>
            <div class="col-xs-3">
              <div class="form-group">
                <label for="end_date" class="">To:</label>
                <input type="date" placeholder="To" name="end_date" id="end_date" class="form-control">
              </div>
            </div>
            <div class="col-xs-3">
              <div class="form-group">
                <label for="location" class="">Where:</label>
                <input type="text" placeholder="City" name="location" id="location" class="form-control">
              </div>
            </div>
            <div class="col-xs-3">
              <div class="form-group submit-btn">
                <input type="submit" value="Find your pony" class="btn btn-brand btn-home">
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>


  <div class="row">
    <div class="col-xs-4">
      <h2 class="home-ponies-title">Ponies</h2>
    </div>
  </div>
  <div class="row">
    <% @pony_offers.each do |offer|  %>
      <div class="col-xs-4">
        <div class="offer-card">
          <div class="card-img" style="background-image: url('<%= cl_image_path offer.pony.photo.path, width: 320, height: 240, crop: :fill %>')">
            <%= link_to "", pony_pony_offer_path(offer.pony, offer) %>
         </div>
          <h4> <%= offer.pony.name %> </h4>
          <p> <%= offer.pony.location  %></p>
          <p> <strong> <%= offer.daily_rate  %> €/day </strong> </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/search.html.erb
  <h1> Searching in: <%= @location %> </h1>





  <h1> <strong> <%= @booking.start_date %> <%= @booking.end_date  %> </strong> </h1>

<% @ponies.each do |pony| %>

  <ul>
    <li> Name:<%= pony.name %> - Location:<%= pony.location %> </li>
  </ul>

<% end  %>





<% @available_offers.each do |offer| %>
<ul>
<li> <%= offer.pony.name  %> <%= offer.start_date  %> <%= offer.end_date  %> </li>
</ul>
<% end %>