config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  get 'search', to: "pages#search", as: "search"

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   registrations: 'users/registrations' }

  root to: 'pages#home'



  resources :pony_offers, only: [:index, :destroy]
  resources :bookings, only: [:index, :show]



  resources :ponies do
    resources :pony_offers, only: [:new, :create, :list, :show ] do
      resources :bookings, except: [ :update, :edit, :index ]
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pony.rb
class Pony < ApplicationRecord
  belongs_to :user
  has_many :pony_offers, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true

  has_attachment :photo

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  def is_owner?(a_user)
    if a_user
      self.user.id == a_user.id
    else
      false
    end
  end
end

app/controllers/ponies_controller.rb
class PoniesController < ApplicationController
  def index
   @pony = Pony.where(user_id: current_user.id)
  end

  def show
    @pony = Pony.find(params[:id])
  end

  def new
    @pony = Pony.new
  end

  def create
    @pony = Pony.new(pony_params)
    @pony.user = current_user
    if @pony.save
      redirect_to pony_path(@pony)
    else
      @error = @pony.errors
      render :new
    end
  end

  def edit
    @pony = Pony.find(params[:id])
  end

  def update
    Pony.find(params[:id]).update(pony_params)
    redirect_to pony_path
  end

  def destroy
    Pony.find(params[:id]).destroy
    redirect_to ponies_path
  end


  private

  def pony_params
    params.require(:pony).permit(:name, :description, :race, :color, :location, :photo)
  end
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/views/ponies/_new_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for @pony do |f| %>
        <div class="form-group">
          <%= f.input :name, label: "Please enter the name of your pony: ", input_html: {class: "form-control"} %>
        </div>
        <div class="form-group">
        <%= f.input :color, label: "Please enter your color: ", as: :text, input_html: {class: "form-control"} %>
        </div>
        <div class="form-group">
        <%= f.input :race, label: "Please enter your pony's race: ", as: :text, input_html: {class: "form-control"} %>
        </div>
        <div class="form-group">
          <%= f.input :description, label: "Please describe your pony: ", as: :text, input_html: {class: "form-control"} %>
        </div>
        <div class="form-group">
            <%= f.input :location, label: "Please give the location of your pony: ", as: :text, input_html: {class: "form-control"} %>
        </div>
        <%= f.input :photo, as: :attachinary %>

        <br>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/ponies/create.html.erb
<h1>Ponies#create</h1>
<p>Find me in app/views/ponies/create.html.erb</p>

app/views/ponies/destroy.html.erb
<h1>Ponies#destroy</h1>
<p>Find me in app/views/ponies/destroy.html.erb</p>

app/views/ponies/edit.html.erb
<div class="container">
  <h1>Edit your pony</h1>
</div>
<%= render 'new_form', pony: @pony %>

app/views/ponies/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p id="notice"><%= notice %></p>
      <h3>My registered ponies</h3>
      <table class="table table-inverse">
        <thead>
          <tr>
            <th scope="row">Name</th>
            <th scope="row">Color</th>
            <th scope="row">Description</th>
            <th scope="row">Location</th>
            <th scope="row">Race</th>
          </tr>
        </thead>
        <tbody>
          <% @pony.each do |pony| %>
            <tr>
              <td><%= pony.name %></td>
              <td><%= pony.color %></td>
              <td><%= pony.description %></td>
              <td><%= pony.location %></td>
              <td><%= pony.race %></td>
              <td><%= link_to 'Show', pony_path(pony) %></td>
              <td><%= link_to 'Edit', edit_pony_path(pony) %></td>
              <td><%= link_to 'Destroy', pony_path(pony), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><%= link_to 'List Pony', new_pony_pony_offer_path(pony)%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to 'New Pony', new_pony_path, class:"btn btn-primary" %>
      <br>
      <br>
      <%= link_to "My Listings", pony_offers_path, class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/ponies/new.html.erb
<div class="container">
  <h1>Create your pony</h1>
</div>

<%= render 'new_form'%>

app/views/ponies/show.html.erb
  <br>
  <br>
  <br>
  <br>
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= cl_image_tag @pony.photo.path, width: 300, height: 300, crop: :fill unless @pony.photo.nil?%>
    </div>
    <div class="col-xs-4">
        <% %w(name color age race description location). each do |method|  %>
          <% value = @pony[method.to_sym]  %>
          <% unless value.nil? || value.strip == "" %>
            <p> <strong><%= method.capitalize %></strong> - <%= value %> </p>
          <% end %>
        <% end %>
    </div>
  </div>
  <br>
  <%= link_to "My Ponies", ponies_path, class:"btn btn-primary" %>
  <br>
  <br>
  <%= link_to "My Listings", pony_offers_path, class:"btn btn-primary" %>
</div>

app/views/ponies/update.html.erb
<h1>Ponies#update</h1>
<p>Find me in app/views/ponies/update.html.erb</p>